[project]
name = "estate-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "reportlab>=4.2.5",
    "streamlit-authenticator>=0.4.1",
]
